### ISSUE TITLE
Player Model Change

### ISSUE THREAD

**Issue by tupac94400** [sneakyevil/SleepingDogs-ModMenu#6] opened 2023-03-18 00:02 UTC
hello, would it be possible to add the possibility of replacing wei with all the characters in the game please, that would be great :)

**Comment by sneakyevil** [comment] 2023-03-27 21:54
I had something done before while doing MP Mod, but would require me to hook up around GlobalProperties to initialize original Wei data instead the data for the certain models. 
Might add it later if I gonna even bother.

**Comment by VertofChest** [comment] 2023-04-09 08:28
Something interesting I noticed: If I spawned WeiBeatCop (iirc) NPC, they would just be a duplicate of the player. If you kicked, they kicked. If you punched, they punched. if you got near a gun, the prompt to pick up the gun would result in them picking up the gun, too
So you could have a clone of yourself but it wouldn't be a bodyguard... strangest thing ever

**Comment by KabetzuriBoii** [comment] 2023-04-11 22:33
> Something interesting I noticed: If I spawned WeiBeatCop (iirc) NPC, they would just be a duplicate of the player. If you kicked, they kicked. If you punched, they punched. if you got them near a gun, the prompt to pick up the gun would appear for you, and if you pressed it, resulted in them picking up the gun, too So you could have a clone of yourself but it wouldn't be a bodyguard... strangest thing ever

funny sheesh ! xD . i just find it amazing that sleeping dogs finally has a mod menue 
;D

**Comment by sneakyevil** [comment] 2023-05-23 20:46
Added in latest release: https://github.com/sneakyevil/SleepingDogs-ModMenu/releases/tag/v1.6.0

**Closed by sneakyevil** 2023-05-23 20:46 UTC
Labels: enhancement
